### ISSUE TITLE
Define Models for common fields.

### ISSUE THREAD

**Issue by naody** [Ethiopia-COVID19/api-gateway#20]
To avoid redundancy, create stand alone Model for commonly used fields.

Example:
[Address](https://github.com/Ethiopia-COVID19/api-gateway/blob/master/models/Address.js) used as [community.address](https://github.com/Ethiopia-COVID19/api-gateway/blob/master/models/Community.js#L15) as an example.

Models: (not restricted to the list below)
- Person (fields like: firstName, middleName, lastName, sex, age....)
- UnderlyingCondition (UnderlyingConditions defined in Community, Passengers...)

**Comment by naody** [comment]
@abelhbeyene, would it also make sense to move [Address](https://github.com/Ethiopia-COVID19/api-gateway/blob/master/models/Address.js) and [Symptom](https://github.com/Ethiopia-COVID19/api-gateway/blob/master/models/Symptom.js) to common?  If so move them to the common directory and update all the references.

**Comment by abelhbeyene** [comment]
@naody - yep will move 'em. I raised a PR so we're on the same page of the approach. That PR wasn't ready so it may break something. Will get it resolved.
