### ISSUE TITLE
The README and the schema.js are not consistent

### ISSUE THREAD

**Issue by SamAsEnd** [Ethiopia-COVID19/api-gateway#9]
The data structure on the readme suggests the `createdBy` attribute has an `id` but not included in the [schema.js](https://github.com/Ethiopia-COVID19/api-gateway/blob/master/schema.js#L183)

**Comment by SamAsEnd** [comment]
README.md
```
...
"createdBy": {
    "id": 1,
...
```

**Comment by SamAsEnd** [comment]
@naody ...

**Comment by naody** [comment]
Missing schema field definitions added.
